language: cpp
dist: xenial

compiler:
  - gcc

before_install:
  - docker pull tkoskela/vlasiator_ci:alpha_v0.4

script:
  - docker run tkoskela/vlasiator_ci:alpha_v0.4 /bin/bash -c "git pull && make clean && make -j 2 testpackage"
 # - docker run tkoskela/vlasiator_ci:alpha_v0.4 /bin/bash -c "git pull && make -j 4 testpackage && cp vlasiator testpackage/ && cd testpackage && ./small_test_docker.sh"
