language: cpp
dist: xenial

compiler:
  - gcc

before_install:
  - docker pull tkoskela/vlasiator_ci:alpha_v0.3

script:
  - docker run tkoskela/vlasiator_ci:alpha_v0.3 /bin/bash -c "git pull && make -j 4 testpackage"
  #- docker run tkoskela/vlasiator_ci:alpha_v0.3 /bin/bash -c "git pull && make -j 4 testpackage && cp vlasiator testpackage/ && cd testpackage && ./small_test_docker.sh"
